### ISSUE TITLE
New To-Do:

### ISSUE THREAD

**Issue by mikebeaton** [mikebeaton/OpenCorePkg#1]
- [x] Rename `OC_ATTR_DEBUG_DISPLAY` -> `OC_ATTR_SHOW_DEBUG_DISPLAY`
 - [x] Add and implement `OC_ATTR_USE_MINIMAL_UI` which hides Shutdown and Restart buttons in both pickers
 - [x] Actually implement check for minimum allowed version of Apple Event (https://github.com/acidanthera/OpenCorePkg/blob/master/Include/Apple/Protocol/AppleEvent.h#L103)
 - [x] At same time, make it an "OCAE:" message if waiting for connect
 - [x] CTRL-held remove UI display when security flag disables action
 - [x] Both pickers: show OC version on existing flag (already works in builtin) ~but in show auxiliary mode only (which will be change for builtin)~
